CREATE TABLE `clinic_merged_export` (
  `patientid` text,
  `patient firstname` text,
  `patient middleinitial` text,
  `patient lastname` text,
  `patient name` text,
  `patient namesuffix` text,
  `patientdob` text,
  `patientlastseend` text,
  `ethnicity` text,
  `ptnt cnty` text,
  `pat gender` text,
  `agriworker` text,
  `familysize` text,
  `familysizedeclined` text,
  `homelessstatus` text,
  `income` text,
  `incomedeclined` text,
  `patient address1` text,
  `patient address2` text,
  `incomelevel` text,
  `patient age` text,
  `patient city` text,
  `patientdeceaseddt` text,
  `ptnt d lvl` text,
  `firstapptdate` text,
  `patient first name used` text,
  `patient former lastname` text,
  `pat gender identity` text,
  `patient homephone` text,
  `patientincome incomeperpayp...` text,
  `patientincome familysize` text,
  `patientincome federalpovert...` text,
  `patientincome lastmodified` text,
  `patient lang` text,
  `ptnt lgcy ptnt d` text,
  `patient marital status` text,
  `patientnextapptyn` text,
  `patient preferred name` text,
  `pat pronouns` text,
  `HCC RAF score` text,
  `race` text,
  `multiple races` text,
  `ref source` text,
  `patientsex` text,
  `pat sex orientation` text,
  `patient state` text,
  `status` text,
  `ptnt trnsprttn t ccc` text,
  `ptnt wrk stts` text,
  `patient zip` text,
  `pblchouspat` text,
  `schoolbased` text,
  `vetstatus` text,
  `prim prvdrfullnme` text,
  `prim prvdr spclty` text
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
