CREATE TABLE `pantry_export` (
  `Visit Date` text,
  `Client ID` text,
  `Client Status` text,
  `Client First Visit- Personal Tab` text,
  `Client First Visit-Date` text,
  `Client Last Name` text,
  `Client First Name` text,
  `Client Preferred Agency` text,
  `Client Date of Birth` text,
  `Client Estimated Date of Birth` text,
  `Client Age` text,
  `Client Gender Identity-Labels` text,
  `Client Gender Identity-Parent Types` text,
  `Client Marital Status` text,
  `Client Email Addresses` text,
  `Client Phone Numbers` text,
  `Client Referred By` text,
  `Client Ethnicity-Labels` text,
  `Client Ethnicity-Parent Types` text,
  `Client Disability` text,
  `Client Landing Date` text,
  `Client Self-Identifies As` text,
  `Client Is Student` text,
  `Client Employment` text,
  `Client School Attended` text,
  `Client School Id` text,
  `Client Grade Documentation` text,
  `Client Grade Documentation Expiration` text,
  `Highest Education Level` text,
  `Country of Highest Education` text,
  `Client Church` text,
  `Client Full Time Employment` text,
  `Client No Income` text,
  `Client Other Income` text,
  `Client Part Time Employment` text,
  `Client Pension` text,
  `Client Public Assistance` text,
  `Client Social Security Disability (SSI/SSDI)` text,
  `Client Social Security Retirement` text,
  `Client Social Security Survivor Benefits` text,
  `Client Student Loans` text,
  `TEFAP  Eligibility` text,
  `Street` text,
  `Line 2` text,
  `City` text,
  `County` text,
  `State` text,
  `Zip Code` text,
  `Housing Type` text,
  `Household ID` text,
  `Household Size` text,
  `Household Languages` text,
  `Household Primary Income Source` text,
  `Monthly Household Income` text,
  `Total Monthly Expenses` text,
  `Total Monthly Net Income` text,
  `Dietary Considerations` text,
  `Social Assistance` text,
  `HH Mem 1- ID` text,
  `HH Mem 1- Status` text,
  `HH Mem 1- Last Name` text,
  `HH Mem 1- First Name` text,
  `HH Mem 1- Date of Birth` text,
  `HH Mem 1- Estimated Date of Birth` text,
  `HH Mem 1- Age` text,
  `HH Mem 1- Gender Identity-Labels` text,
  `HH Mem 1- Gender Identity-Parent Types` text,
  `HH Mem 1- Phone Numbers` text,
  `HH Mem 1- Ethnicity-Labels` text,
  `HH Mem 1- Ethnicity-Parent Types` text,
  `HH Mem 1- Disability` text,
  `HH Mem 1- Landing Date` text,
  `HH Mem 1- Self-Identifies As` text,
  `HH Mem 1- Is Student` text,
  `HH Mem 1- Employment` text,
  `HH Mem 1- School Attended` text,
  `HH Mem 1- School Id` text,
  `HH Mem 1- Grade Documentation` text,
  `HH Mem 1- Grade Documentation Expiration` text,
  `HH Mem 1- Relationship to Main Client` text,
  `HH Mem 1- Church` text,
  `HH Mem 1- Full Time Employment` text,
  `HH Mem 1- No Income` text,
  `HH Mem 1- Other Income` text,
  `HH Mem 1- Part Time Employment` text,
  `HH Mem 1- Pension` text,
  `HH Mem 1- Public Assistance` text,
  `HH Mem 1- Social Security Disability (SSI/SSDI)` text,
  `HH Mem 1- Social Security Retirement` text,
  `HH Mem 1- Social Security Survivor Benefits` text,
  `HH Mem 1- Student Loans` text,
  `HH Mem 2- ID` text,
  `HH Mem 2- Status` text,
  `HH Mem 2- Last Name` text,
  `HH Mem 2- First Name` text,
  `HH Mem 2- Date of Birth` text,
  `HH Mem 2- Estimated Date of Birth` text,
  `HH Mem 2- Age` text,
  `HH Mem 2- Gender Identity-Labels` text,
  `HH Mem 2- Gender Identity-Parent Types` text,
  `HH Mem 2- Phone Numbers` text,
  `HH Mem 2- Ethnicity-Labels` text,
  `HH Mem 2- Ethnicity-Parent Types` text,
  `HH Mem 2- Disability` text,
  `HH Mem 2- Landing Date` text,
  `HH Mem 2- Self-Identifies As` text,
  `HH Mem 2- Is Student` text,
  `HH Mem 2- Employment` text,
  `HH Mem 2- School Attended` text,
  `HH Mem 2- School Id` text,
  `HH Mem 2- Grade Documentation` text,
  `HH Mem 2- Grade Documentation Expiration` text,
  `HH Mem 2- Relationship to Main Client` text,
  `HH Mem 2- Church` text,
  `HH Mem 2- Full Time Employment` text,
  `HH Mem 2- No Income` text,
  `HH Mem 2- Other Income` text,
  `HH Mem 2- Part Time Employment` text,
  `HH Mem 2- Pension` text,
  `HH Mem 2- Public Assistance` text,
  `HH Mem 2- Social Security Disability (SSI/SSDI)` text,
  `HH Mem 2- Social Security Retirement` text,
  `HH Mem 2- Social Security Survivor Benefits` text,
  `HH Mem 2- Student Loans` text,
  `HH Mem 3- ID` text,
  `HH Mem 3- Status` text,
  `HH Mem 3- Last Name` text,
  `HH Mem 3- First Name` text,
  `HH Mem 3- Date of Birth` text,
  `HH Mem 3- Estimated Date of Birth` text,
  `HH Mem 3- Age` text,
  `HH Mem 3- Gender Identity-Labels` text,
  `HH Mem 3- Gender Identity-Parent Types` text,
  `HH Mem 3- Phone Numbers` text,
  `HH Mem 3- Ethnicity-Labels` text,
  `HH Mem 3- Ethnicity-Parent Types` text,
  `HH Mem 3- Disability` text,
  `HH Mem 3- Landing Date` text,
  `HH Mem 3- Self-Identifies As` text,
  `HH Mem 3- Is Student` text,
  `HH Mem 3- Employment` text,
  `HH Mem 3- School Attended` text,
  `HH Mem 3- School Id` text,
  `HH Mem 3- Grade Documentation` text,
  `HH Mem 3- Grade Documentation Expiration` text,
  `HH Mem 3- Relationship to Main Client` text,
  `HH Mem 3- Church` text,
  `HH Mem 3- Full Time Employment` text,
  `HH Mem 3- No Income` text,
  `HH Mem 3- Other Income` text,
  `HH Mem 3- Part Time Employment` text,
  `HH Mem 3- Pension` text,
  `HH Mem 3- Public Assistance` text,
  `HH Mem 3- Social Security Disability (SSI/SSDI)` text,
  `HH Mem 3- Social Security Retirement` text,
  `HH Mem 3- Social Security Survivor Benefits` text,
  `HH Mem 3- Student Loans` text,
  `HH Mem 4- ID` text,
  `HH Mem 4- Status` text,
  `HH Mem 4- Last Name` text,
  `HH Mem 4- First Name` text,
  `HH Mem 4- Date of Birth` text,
  `HH Mem 4- Estimated Date of Birth` text,
  `HH Mem 4- Age` text,
  `HH Mem 4- Gender Identity-Labels` text,
  `HH Mem 4- Gender Identity-Parent Types` text,
  `HH Mem 4- Phone Numbers` text,
  `HH Mem 4- Ethnicity-Labels` text,
  `HH Mem 4- Ethnicity-Parent Types` text,
  `HH Mem 4- Disability` text,
  `HH Mem 4- Landing Date` text,
  `HH Mem 4- Self-Identifies As` text,
  `HH Mem 4- Is Student` text,
  `HH Mem 4- Employment` text,
  `HH Mem 4- School Attended` text,
  `HH Mem 4- School Id` text,
  `HH Mem 4- Grade Documentation` text,
  `HH Mem 4- Grade Documentation Expiration` text,
  `HH Mem 4- Relationship to Main Client` text,
  `HH Mem 4- Church` text,
  `HH Mem 4- Full Time Employment` text,
  `HH Mem 4- No Income` text,
  `HH Mem 4- Other Income` text,
  `HH Mem 4- Part Time Employment` text,
  `HH Mem 4- Pension` text,
  `HH Mem 4- Public Assistance` text,
  `HH Mem 4- Social Security Disability (SSI/SSDI)` text,
  `HH Mem 4- Social Security Retirement` text,
  `HH Mem 4- Social Security Survivor Benefits` text,
  `HH Mem 4- Student Loans` text,
  `HH Mem 5- ID` text,
  `HH Mem 5- Status` text,
  `HH Mem 5- Last Name` text,
  `HH Mem 5- First Name` text,
  `HH Mem 5- Date of Birth` text,
  `HH Mem 5- Estimated Date of Birth` text,
  `HH Mem 5- Age` text,
  `HH Mem 5- Gender Identity-Labels` text,
  `HH Mem 5- Gender Identity-Parent Types` text,
  `HH Mem 5- Phone Numbers` text,
  `HH Mem 5- Ethnicity-Labels` text,
  `HH Mem 5- Ethnicity-Parent Types` text,
  `HH Mem 5- Disability` text,
  `HH Mem 5- Landing Date` text,
  `HH Mem 5- Self-Identifies As` text,
  `HH Mem 5- Is Student` text,
  `HH Mem 5- Employment` text,
  `HH Mem 5- School Attended` text,
  `HH Mem 5- School Id` text,
  `HH Mem 5- Grade Documentation` text,
  `HH Mem 5- Grade Documentation Expiration` text,
  `HH Mem 5- Relationship to Main Client` text,
  `HH Mem 5- Church` text,
  `HH Mem 5- Full Time Employment` text,
  `HH Mem 5- No Income` text,
  `HH Mem 5- Other Income` text,
  `HH Mem 5- Part Time Employment` text,
  `HH Mem 5- Pension` text,
  `HH Mem 5- Public Assistance` text,
  `HH Mem 5- Social Security Disability (SSI/SSDI)` text,
  `HH Mem 5- Social Security Retirement` text,
  `HH Mem 5- Social Security Survivor Benefits` text,
  `HH Mem 5- Student Loans` text,
  `HH Mem 6- ID` text,
  `HH Mem 6- Status` text,
  `HH Mem 6- Last Name` text,
  `HH Mem 6- First Name` text,
  `HH Mem 6- Date of Birth` text,
  `HH Mem 6- Estimated Date of Birth` text,
  `HH Mem 6- Age` text,
  `HH Mem 6- Gender Identity-Labels` text,
  `HH Mem 6- Gender Identity-Parent Types` text,
  `HH Mem 6- Phone Numbers` text,
  `HH Mem 6- Ethnicity-Labels` text,
  `HH Mem 6- Ethnicity-Parent Types` text,
  `HH Mem 6- Disability` text,
  `HH Mem 6- Landing Date` text,
  `HH Mem 6- Self-Identifies As` text,
  `HH Mem 6- Is Student` text,
  `HH Mem 6- Employment` text,
  `HH Mem 6- School Attended` text,
  `HH Mem 6- School Id` text,
  `HH Mem 6- Grade Documentation` text,
  `HH Mem 6- Grade Documentation Expiration` text,
  `HH Mem 6- Relationship to Main Client` text,
  `HH Mem 6- Church` text,
  `HH Mem 6- Full Time Employment` text,
  `HH Mem 6- No Income` text,
  `HH Mem 6- Other Income` text,
  `HH Mem 6- Part Time Employment` text,
  `HH Mem 6- Pension` text,
  `HH Mem 6- Public Assistance` text,
  `HH Mem 6- Social Security Disability (SSI/SSDI)` text,
  `HH Mem 6- Social Security Retirement` text,
  `HH Mem 6- Social Security Survivor Benefits` text,
  `HH Mem 6- Student Loans` text,
  `HH Mem 7- ID` text,
  `HH Mem 7- Status` text,
  `HH Mem 7- Last Name` text,
  `HH Mem 7- First Name` text,
  `HH Mem 7- Date of Birth` text,
  `HH Mem 7- Estimated Date of Birth` text,
  `HH Mem 7- Age` text,
  `HH Mem 7- Gender Identity-Labels` text,
  `HH Mem 7- Gender Identity-Parent Types` text,
  `HH Mem 7- Phone Numbers` text,
  `HH Mem 7- Ethnicity-Labels` text,
  `HH Mem 7- Ethnicity-Parent Types` text,
  `HH Mem 7- Disability` text,
  `HH Mem 7- Landing Date` text,
  `HH Mem 7- Self-Identifies As` text,
  `HH Mem 7- Is Student` text,
  `HH Mem 7- Employment` text,
  `HH Mem 7- School Attended` text,
  `HH Mem 7- School Id` text,
  `HH Mem 7- Grade Documentation` text,
  `HH Mem 7- Grade Documentation Expiration` text,
  `HH Mem 7- Relationship to Main Client` text,
  `HH Mem 7- Church` text,
  `HH Mem 7- Full Time Employment` text,
  `HH Mem 7- No Income` text,
  `HH Mem 7- Other Income` text,
  `HH Mem 7- Part Time Employment` text,
  `HH Mem 7- Pension` text,
  `HH Mem 7- Public Assistance` text,
  `HH Mem 7- Social Security Disability (SSI/SSDI)` text,
  `HH Mem 7- Social Security Retirement` text,
  `HH Mem 7- Social Security Survivor Benefits` text,
  `HH Mem 7- Student Loans` text,
  `HH Mem 8- ID` text,
  `HH Mem 8- Status` text,
  `HH Mem 8- Last Name` text,
  `HH Mem 8- First Name` text,
  `HH Mem 8- Date of Birth` text,
  `HH Mem 8- Estimated Date of Birth` text,
  `HH Mem 8- Age` text,
  `HH Mem 8- Gender Identity-Labels` text,
  `HH Mem 8- Gender Identity-Parent Types` text,
  `HH Mem 8- Phone Numbers` text,
  `HH Mem 8- Ethnicity-Labels` text,
  `HH Mem 8- Ethnicity-Parent Types` text,
  `HH Mem 8- Disability` text,
  `HH Mem 8- Landing Date` text,
  `HH Mem 8- Self-Identifies As` text,
  `HH Mem 8- Is Student` text,
  `HH Mem 8- Employment` text,
  `HH Mem 8- School Attended` text,
  `HH Mem 8- School Id` text,
  `HH Mem 8- Grade Documentation` text,
  `HH Mem 8- Grade Documentation Expiration` text,
  `HH Mem 8- Relationship to Main Client` text,
  `HH Mem 8- Church` text,
  `HH Mem 8- Full Time Employment` text,
  `HH Mem 8- No Income` text,
  `HH Mem 8- Other Income` text,
  `HH Mem 8- Part Time Employment` text,
  `HH Mem 8- Pension` text,
  `HH Mem 8- Public Assistance` text,
  `HH Mem 8- Social Security Disability (SSI/SSDI)` text,
  `HH Mem 8- Social Security Retirement` text,
  `HH Mem 8- Social Security Survivor Benefits` text,
  `HH Mem 8- Student Loans` text,
  `HH Mem 9- ID` text,
  `HH Mem 9- Status` text,
  `HH Mem 9- Last Name` text,
  `HH Mem 9- First Name` text,
  `HH Mem 9- Date of Birth` text,
  `HH Mem 9- Estimated Date of Birth` text,
  `HH Mem 9- Age` text,
  `HH Mem 9- Gender Identity-Labels` text,
  `HH Mem 9- Gender Identity-Parent Types` text,
  `HH Mem 9- Phone Numbers` text,
  `HH Mem 9- Ethnicity-Labels` text,
  `HH Mem 9- Ethnicity-Parent Types` text,
  `HH Mem 9- Disability` text,
  `HH Mem 9- Landing Date` text,
  `HH Mem 9- Self-Identifies As` text,
  `HH Mem 9- Is Student` text,
  `HH Mem 9- Employment` text,
  `HH Mem 9- School Attended` text,
  `HH Mem 9- School Id` text,
  `HH Mem 9- Grade Documentation` text,
  `HH Mem 9- Grade Documentation Expiration` text,
  `HH Mem 9- Relationship to Main Client` text,
  `HH Mem 9- Church` text,
  `HH Mem 9- Full Time Employment` text,
  `HH Mem 9- No Income` text,
  `HH Mem 9- Other Income` text,
  `HH Mem 9- Part Time Employment` text,
  `HH Mem 9- Pension` text,
  `HH Mem 9- Public Assistance` text,
  `HH Mem 9- Social Security Disability (SSI/SSDI)` text,
  `HH Mem 9- Social Security Retirement` text,
  `HH Mem 9- Social Security Survivor Benefits` text,
  `HH Mem 9- Student Loans` text
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
