CREATE TABLE `person` (
  `person_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `last_name` varchar(100) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `middle_name` varchar(100) DEFAULT NULL,
  `preferred_name` varchar(100) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `sex_at_birth` enum('M','F','X','U') DEFAULT NULL,
  `gender_identity` varchar(255) DEFAULT NULL,
  `race` varchar(100) DEFAULT NULL,
  `ethnicity` varchar(255) DEFAULT NULL,
  `marital_status` varchar(50) DEFAULT NULL,
  `primary_language` varchar(50) DEFAULT NULL,
  `email` varchar(254) DEFAULT NULL,
  `phone_e164` varchar(20) DEFAULT NULL,
  `phone_raw` text,
  `address1` varchar(255) DEFAULT NULL,
  `address2` varchar(255) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `state` char(2) DEFAULT NULL,
  `zip` varchar(10) DEFAULT NULL,
  `clinic_patientid` int unsigned DEFAULT NULL,
  `pharmacy_pat_key` int unsigned DEFAULT NULL,
  `pantry_client_id` bigint unsigned DEFAULT NULL,
  `employment_status` varchar(255) DEFAULT NULL,
  `education_level` varchar(100) DEFAULT NULL,
  `housing_type` varchar(100) DEFAULT NULL,
  `homeless_status` enum('Y','N','U') DEFAULT NULL,
  `household_size` tinyint unsigned DEFAULT NULL,
  `monthly_income` decimal(13,2) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`person_id`),
  UNIQUE KEY `uk_person_pantry_client` (`pantry_client_id`),
  UNIQUE KEY `ux_person_name_dob_norm` ((upper(trim(`first_name`))),(upper(trim(`last_name`))),`dob`),
  KEY `idx_pat_dob` (`dob`),
  KEY `idx_pat_zip` (`zip`),
  KEY `fk_person_clinic_export` (`clinic_patientid`),
  KEY `fk_person_pharmacy_export` (`pharmacy_pat_key`)
) ENGINE=InnoDB AUTO_INCREMENT=10238 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;
