CREATE TABLE `pharmacy_pickup_date_export` (
  `PAT KEY` text,
  `STOREID` text,
  `LAST NAME` text,
  `FIRST NAME` text,
  `MIDDLE NAME` text,
  `ADDRESS1` text,
  `ADDRESS2` text,
  `CITY` text,
  `STATE` text,
  `ZIP` text,
  `EMAIL` text,
  `AREA` text,
  `XCHG` text,
  `NBR` text,
  `BIRTHDAY` text,
  `SSN` text,
  `SEX` text,
  `INACTIVE` text,
  `CREATED` text,
  `DRUG NAME` text,
  `NDC` text,
  `NDC 542` text,
  `DT` text,
  `DOC LASTNAME` text,
  `DOC FIRSTNAME` text,
  `DOC ID` text,
  `NPI` text,
  `STOREID_2` text,
  `RX NBR` text,
  `RF` text,
  `RA` text,
  `RL` text,
  `QTY` text,
  `QL` text,
  `DS` text,
  `WRITTEN` text,
  `RX DATE` text,
  `RX TIME` text,
  `RX PICKED UP` text,
  `DAW` text,
  `RPH` text,
  `TECH` text,
  `S` text,
  `TOTAL PRICE` text,
  `CASH PAID` text,
  `PLAN 1` text,
  `PAID` text,
  `PLAN 2` text,
  `PAID_2` text,
  `PLAN 3` text,
  `PAID_3` text,
  `DIRECTION 1` text,
  `DIRECTION 2` text,
  `DIRECTION 3` text,
  `DIRECTION 4` text,
  `DIRECTION 5` text,
  `DOCADD1` text,
  `DOCADD2` text,
  `DOCCITY` text,
  `DOCSTATE` text,
  `DOCZIP` text,
  `Column 1` text
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
