CREATE TABLE `pharmacy_insurance_export` (
  `PAT KEY` text,
  `STOREID` text,
  `LAST NAME` text,
  `FIRST NAME` text,
  `MIDDLE NAME` text,
  `ADDRESS1` text,
  `ADDRESS2` text,
  `CITY` text,
  `STATE` text,
  `ZIP` text,
  `EMAIL` text,
  `AREA` text,
  `XCHG` text,
  `NBR` text,
  `BIRTHDAY` text,
  `SSN` text,
  `SEX` text,
  `INACTIVE` text,
  `CREATED` text,
  `PLAN 1` text,
  `STATUS` text,
  `PLAN 2` text,
  `STATUS_2` text,
  `PLAN 3` text,
  `STATUS_3` text,
  `PLAN 4` text,
  `STATUS_4` text,
  `PLAN 5` text,
  `STATUS_5` text,
  `PLAN 6` text,
  `STATUS_6` text,
  `PLAN 7` text,
  `STATUS_7` text,
  `PLAN 8` text,
  `STATUS_8` text,
  `PLAN 9` text,
  `STATUS_9` text,
  `PLAN 10` text,
  `STATUS_10` text,
  `PLAN 11` text,
  `STATUS_11` text,
  `PLAN 12` text,
  `STATUS_12` text,
  `PLAN 13` text,
  `STATUS_13` text,
  `ALLERGY 1` text,
  `ALLERGY 2` text,
  `ALLERGY 3` text,
  `ALLERGY 4` text,
  `ALLERGY 5` text,
  `ALLERGY 6` text,
  `ALLERGY 7` text,
  `ALLERGY 8` text,
  `ALLERGY 9` text,
  `ALLERGY 10` text,
  `ALLERGY 11` text,
  `ALLERGY 12` text,
  `ALLERGY 13` text,
  `ALLERGY 14` text,
  `ALLERGY 15` text,
  `ALLERGY 16` text,
  `ALLERGY 17` text,
  `ALLERGY 18` text,
  `ALLERGY 19` text,
  `ALLERGY 20` text,
  `ALLERGY 21` text,
  `ALLERGY 22` text,
  `ALLERGY 23` text,
  `ALLERGY 24` text,
  `ALLERGY 25` text,
  `ALLERGY 26` text,
  `ALLERGY 27` text,
  `ALLERGY 28` text,
  `ALLERGY 29` text,
  `ALLERGY 30` text,
  `PATIENT MEMO` text,
  `CELL AREA` text,
  `CELL XCHG` text,
  `CELL NBR` text,
  `LAST RXDATE` text,
  `Column 81` text
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
